# Login page elements
txt_userLoginName = "name:userName"
txt_userPassword = "name:password"
btn_signin = "xpath://input[@name='submit']"

# "link:REGISTER"
# first_name = "xpath://input[@name='firstName']"
# last_name = "name:lastName"
# phone = "name:phone"
# email = "id:userName"
# address = "name:address1"
# city = "name:city"
# province = "name:state"
# postal_code = "name:postalCode"
# country = "name:country"
# user_name = "name:email"
# pwd = "name:password"
# confirm_pwd = "name:confirmPassword"
# submit_btn = "xpath://input[@name='register']"


register_link = "xpath://a[normalize-space()='REGISTER']"
first_name = "xpath://input*[@name='firstName']"
last_name = "xpath://input[@name='firstName']"
phone = "xpath://input[@name='lastName']"
email = "xpath://input[@name='phone']"
address = "xpath://input[@id='userName']"
city = "xpath://input[@name='address1']"
province = "xpath/:/input[@name='city']"
postal_code = "xpath://input[@name='state']"
country = "xpath/:/input[@name='postalCode']"
user_name = "xpath://select[@name='country']"
confirm_pwd = "xpath://select[@name='country']"
submit_btn = "xpath://input[@id='email']"
